[package]
name = "hamming"
require="hamming.lua"
version = "1.0"
summary = "A package that provides a Hamming distance function"
license = "GPL-3.0"
repository = "https://github.com/coalio/me-at-the-zoo"
maintainer = "Coal <dibashtori@gmail.com>"

[demo]
main="hamming_demo.lua"
lua_version=["LuaJIT2.0", "Lua5.3", "*"]

[support]
lua_version = ["*"]
platform = ["*"]